export const discoverDB = [
    {
      id: 0,
      title: "Animation",
      desc: "Perfect your craft with the same tools used at Dreamworks and Pixar.",
      icon: "https://ucarecdn.com/15b40295-8ba7-4462-bd11-d7b4c6353922/animation.svg",
      tags: ["blender", "spark ar", "3d model"],
      color: "bg-[#23a094]",
    },
    {
      id: 1,
      title: "Audio",
      desc: "Open your ears and mind to interviews, meditations, and true crime thrillers.",
      icon: "https://ucarecdn.com/a3386fbd-7da9-4d0b-9583-11240ae029fe/audio.svg",
      tags: ["meditation", "hypnosis", "subliminal messages"],
      color: "bg-[#e2442f]",
    },
    {
      id: 2,
      title: "Business & Money",
      desc: "Learn to earn in an increasingly unpredictable world.",
      icon: "https://ucarecdn.com/8d9ca7c3-501d-4080-9086-a395cdf8ed54/business.svg",
      tags: ["notion template", "investing", "instagram"],
      color: "bg-[#23a094]",
    },
    {
      id: 3,
      title: "Comics & Graphic Novels",
      desc: "Sequential art with loads of heart. Welcome to a paradise of panels.",
      icon: "https://ucarecdn.com/41969327-df35-40be-8a27-c3287ce10dfe/art.svg",
      tags: ["comic", "manga", "anime"],
      color: "bg-[#f1f333]",
    },
    {
      id: 4,
      title: "Design",
      desc: "Code, design, and ship your dream product with these technical resources.",
      icon: "https://ucarecdn.com/2a796c5c-af57-4cbf-8731-744430b0f8b6/design.svg",
      tags: ["textures", "mockup", "font"],
      color: "bg-[#ffc900]",
    },
    {
      id: 5,
      title: "Drawing & Painting",
      desc: "Tutorials, plugins, and brushes from pro concept artists and illustrators.",
      icon: "https://ucarecdn.com/cb34c701-c465-4b51-96ac-dc0e2150dec4/drawing.svg",
      tags: ["procreate", "brushes", "art"],
      color: "bg-[#90a8ed]",
    },
    {
      id: 6,
      title: "Education",
      desc: "Pick up a new skill with courses and guides from world-class pros.",
      icon: "https://ucarecdn.com/133e088e-bbac-48ab-aaf0-29f826cdb0a9/edu.svg",
      tags: ["education", "certification", "examslearning"],
      color: "bg-[#23a094]",
    },
    {
      id: 7,
      title: "Fiction Books",
      desc: "Short stories, novellas, and epic tomes full of interesting characters and worlds.",
      icon: "https://ucarecdn.com/44507c2b-12fd-45e1-9d9d-84c891fd56f6/fiction.svg",
      tags: ["sci-fi", "poetry", "fiction"],
      color: "bg-[#90a8ed]",
    },
    {
      id: 8,
      title: "Films",
      desc: "Have a movie night with some of the best stories to hit the small screen.",
      icon: "https://ucarecdn.com/0dc6f83a-9dbc-4f96-b508-7dff38c6b7e7/film.svg",
      tags: ["after effects", "vj loops", "luts"],
      color: "bg-[#e2442f]",
    },
    {
      id: 9,
      title: "Fitness & Health",
      desc: "Whether you’re looking to shed or shred, here are coaches to pump you up.",
      icon: "https://ucarecdn.com/36547f7d-e53b-4739-b1f4-3e11a4da110c/fitness.svg",
      tags: ["fitness", "workout program", "yoga"],
      color: "bg-[#ffc900]",
    },
  ];